### ISSUE TITLE
"file" argument must be a non-empty string

### ISSUE THREAD

**Issue by ISNIT0** [skepticfx/node-radamsa#2]
When importing node-radamsa (`require('node-radamsa')`) the following error occurs:
Code:
```javascript
const radamsa = require('node-radamsa');
```

![image](https://user-images.githubusercontent.com/5173131/32940964-173b7a52-cb7c-11e7-97dc-7b7f994ef498.png)
```
TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:381:11)
    at spawnSync (child_process.js:510:38)
    at execSync (child_process.js:626:13)
    at sh (/Users/user/Projects/kafkaTools/node_modules/node-radamsa/index.js:5:10)
    at Object.<anonymous> (/Users/user/Projects/kafkaTools/node_modules/node-radamsa/index.js:9:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

Node Version:
![image](https://user-images.githubusercontent.com/5173131/32940991-3262201a-cb7c-11e7-80ec-6a4bb7fe2836.png)

Radamsa Version:
![image](https://user-images.githubusercontent.com/5173131/32941009-4753e256-cb7c-11e7-9f46-7129fcc811e0.png)

node-radamsa Version:
![image](https://user-images.githubusercontent.com/5173131/32941224-f7f7b344-cb7c-11e7-8d14-ebe75b500fc6.png)

**Comment by skepticfx** [comment]
Hi @ISNIT0 

Thanks for filing this. I am looking into this now.

I tried this using the following code and thing work fine for on the latest node, npm and radamsa (same version as yours)

```
➜  test cat index.js 
const radamsa = require('node-radamsa');
const fuzzed = radamsa.run('index.js', '-n', '10');
console.log(fuzzed);

➜  test cat package.json 
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "node-radamsa": "^0.4.0"
  }
}


➜  test node index.js 
const radamsa.run('index.js', '-n', '0''0');
console.log(fuzzed);
const fuzzed = radamsa.run('index.js', '-n', '340282366920938463463374607431768211702');
```

Can you show me your test code? Does this happen even when you just do a `require('node-radamsa')` ?

**Comment by ISNIT0** [comment]
I think it ended up being something to do with the execSync: https://github.com/skepticfx/node-radamsa/blob/master/index.js#L5

I couldn't get the code working even by copying bits of the code separately, so I made my own version of sh and called it directly: https://github.com/ISNIT0/kafka-testing-tools/blob/master/fuzz/fuzz.js

I would suggest it's probably from node-lib changes. The error was caused by calling: https://github.com/skepticfx/node-radamsa/blob/master/index.js#L9 But the issue was with node, not radamsa. I'll have another attempt at reproing later today for you.

**Comment by ISNIT0** [comment]
This code is causing the issue:
```javascript
var execSync = require('child_process').execSync;
var sh = function () {
    return execSync([].slice.apply(arguments), {
        'stdio': 'pipe'
    }).toString();
}

var version = sh('radamsa -V');
```

execSync seems to want a `string`, rather than a `string[]`.

I don't see any history of this function taking a `string[]`: https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options
Is that code definitely working on your machine?

Very odd. I suppose we can't just make the change, incase there's a version out there that wants an array?
